version: "3.7"

services:
  deno:
    image: "deno-docker:1.4.6"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ""
    command: ["denon", "start"]
    networks: 
      - deno
    
networks:
  deno: {}